#!/usr/bin/env Rscript
# Render the participant files used for instructor demonstrations.

ROOT <- tryCatch(system2("git", c("rev-parse", "--show-toplevel"), stdout = TRUE),
                 error = function(e) getwd())
setwd(ROOT)

# Quarto skips project inputs in dot-prefixed directories.
BUILD <- "demos-build"
OUT   <- "_site/demos"

# `staged`: files copied into a generated project under demos-build/<name>/.
# `project`: an existing Quarto project rendered in place.
groups <- list(
  day1 = list(
    stage = c(
      "exercises/day1-intro/authoring-starter.qmd",
      "exercises/day1-intro/authoring-checkpoint.qmd",
      "exercises/day1-intro/parameters-starter.qmd",
      "exercises/day1-intro/sample-typst.qmd",
      "exercises/day1-intro/references.bib",
      "exercises/day1-intro/apa.csl",
      "exercises/day1-intro/_brand.yml"
    )
  ),
  day1_solutions = list(
    stage = c(
      "exercises/solutions/day1/penguins-report.qmd",
      "exercises/solutions/day1/penguins-by-species.qmd",
      "exercises/solutions/day1/references.bib",
      "exercises/solutions/day1/apa.csl",
      "exercises/solutions/day1/_brand.yml"
    )
  ),
  day2 = list(project = "exercises/solutions/day2")
)

out_name <- c(day1 = "day1", day1_solutions = "day1-solutions", day2 = "day2-solution")
out_title <- c(day1           = "Day 1 &mdash; working folder",
               day1_solutions = "Day 1 &mdash; finished documents",
               day2           = "Day 2 &mdash; finished website")

up_to_root <- function(from) strrep("../", length(strsplit(from, "/", fixed = TRUE)[[1]]))

quarto <- function(args) {
  status <- system2("quarto", args)
  if (status != 0L) stop("quarto render failed: quarto ", paste(args, collapse = " "), call. = FALSE)
}

render_staged <- function(name, files) {
  dir <- file.path(BUILD, name)
  unlink(dir, recursive = TRUE, force = TRUE)   # clean rebuild so removed files disappear
  dir.create(dir, recursive = TRUE, showWarnings = FALSE)
  for (f in files) {
    if (!file.exists(f)) stop("demo source missing: ", f, call. = FALSE)
    file.copy(f, file.path(dir, basename(f)), overwrite = TRUE, copy.mode = FALSE)
  }
  writeLines(c(
    "# Generated by tools/render-demos.R -- edit that script, not this file.",
    "project:",
    "  type: default",
    sprintf("  output-dir: %s%s/%s", up_to_root(dir), OUT, out_name[[name]])
  ), file.path(dir, "_quarto.yml"))
  quarto(c("render", dir))
}

render_project <- function(name, dir) {
  quarto(c("render", dir, "--output-dir",
           sprintf("%s%s/%s", up_to_root(dir), OUT, out_name[[name]])))
}

wanted <- commandArgs(trailingOnly = TRUE)
if (length(wanted)) {
  unknown <- setdiff(wanted, names(groups))
  if (length(unknown)) {
    stop("unknown demo group: ", paste(unknown, collapse = ", "),
         " (known: ", paste(names(groups), collapse = ", "), ")", call. = FALSE)
  }
} else {
  wanted <- names(groups)
}

for (name in wanted) {
  g <- groups[[name]]
  if (!is.null(g$stage)) render_staged(name, g$stage) else render_project(name, g$project)
  cat(sprintf("render-demos: %s -> %s/%s\n", name, OUT, out_name[[name]]))
}

links <- character()
for (name in names(groups)) {
  dir <- file.path(OUT, out_name[[name]])
  if (!dir.exists(dir)) next
  # Include optional pages omitted from the navbar, but not nested report pages.
  rel <- sort(list.files(dir, pattern = "\\.(html|pdf)$"))
  rel <- c(intersect("index.html", rel), setdiff(rel, "index.html"))
  links <- c(links,
             sprintf("<h2>%s</h2>", out_title[[name]]),
             "<ul>",
             sprintf("<li><a href=\"%s/%s\">%s/%s</a></li>", out_name[[name]], rel,
                     out_name[[name]], rel),
             "</ul>")
}
writeLines(c(
  "<!DOCTYPE html>",
  "<html lang=\"en\"><head><meta charset=\"utf-8\">",
  "<title>RaukR 2026 Quarto -- demo documents</title>",
  "<style>body{font-family:system-ui,sans-serif;max-width:44rem;margin:3rem auto;padding:0 1rem}",
  "h2{font-size:1.1rem;margin-top:2rem}li{margin:.3rem 0}</style>",
  "</head><body>",
  "<h1>Demo documents</h1>",
  "<p>The finished lab documents, rendered as participants render them. This page is not linked",
  "from the course site.</p>",
  links,
  "</body></html>"
), file.path(OUT, "index.html"))
cat(sprintf("render-demos: hub page -> %s/index.html\n", OUT))
