#!/usr/bin/env Rscript
# render-demos.R -- render the finished lab documents into _site/demos/ so they can be shown on
# screen from a URL during the sessions.
#
# These pages are deployed but NOT linked from the site (no navbar entry, no lab-page link): they
# are the instructor's demo material, not a shortcut past the exercises.
#
# Sources are the generated `exercises/` payload, not `labs/`, so what appears on screen is what
# participants downloaded (`just exercises-check` guards that exercises/ matches labs/).
#
# Why a script rather than a few `quarto render` lines in the justfile: `--output-dir` only works
# for PROJECT renders, and the Day-1 files deliberately have no `_quarto.yml` (see
# .claude/rules/exercises.md -- their whole point is to render standalone). So each Day-1 group is
# staged into a throwaway project under .demos-build/ with a generated `_quarto.yml`. Staging them
# separately also keeps `_brand.yml` where it belongs: the starters are branded, the Day-1
# solutions are not, exactly as in the payload.
#
# Cross-platform: base R + system2("quarto", ...) only, per .claude/rules/justfile.md.
#
# Usage:
#   Rscript tools/render-demos.R          # render every group
#   Rscript tools/render-demos.R day2     # render one group by name

ROOT <- tryCatch(system2("git", c("rev-parse", "--show-toplevel"), stdout = TRUE),
                 error = function(e) getwd())
setwd(ROOT)

# Gitignored staging area. NOT dot-prefixed: Quarto skips hidden paths when it collects a
# project's inputs, so a `.`-named staging dir renders nothing and exits 0. Each subfolder holds a
# generated `_quarto.yml`, which makes it a separate project the root site render leaves alone.
BUILD <- "demos-build"
OUT   <- "_site/demos"

# ---- groups ------------------------------------------------------------------------------------
# `staged`: files copied into a generated project under .demos-build/<name>/.
# `project`: an existing Quarto project rendered in place.
groups <- list(
  # The Day-1 starting points, branded (sample-typst.qmd reads _brand.yml via read_brand_yml()).
  day1 = list(
    stage = c(
      "exercises/day1-intro/citations-starter.qmd",
      "exercises/day1-intro/parameters-starter.qmd",
      "exercises/day1-intro/sample-typst.qmd",
      "exercises/day1-intro/references.bib",
      "exercises/day1-intro/apa.csl",
      "exercises/day1-intro/_brand.yml"
    )
  ),
  # The Day-1 finished documents. No _brand.yml here -- the payload has none either.
  day1_solutions = list(
    stage = c(
      "exercises/solutions/day1/penguins-report.qmd",
      "exercises/solutions/day1/penguins-by-species.qmd",
      "exercises/solutions/day1/references.bib",
      "exercises/solutions/day1/apa.csl"
    )
  ),
  # The finished Day-2 website -- already a project, so it renders where it stands.
  day2 = list(project = "exercises/solutions/day2")
)

# Output folder per group (also the URL path under /demos/), and its heading on the hub page.
out_name <- c(day1 = "day1", day1_solutions = "day1-solutions", day2 = "day2-solution")
out_title <- c(day1           = "Day 1 &mdash; starting points",
               day1_solutions = "Day 1 &mdash; finished documents",
               day2           = "Day 2 &mdash; finished website")

# ---- helpers -----------------------------------------------------------------------------------
# A relative path from `from` back up to the repo root ("../" per level).
up_to_root <- function(from) strrep("../", length(strsplit(from, "/", fixed = TRUE)[[1]]))

quarto <- function(args) {
  status <- system2("quarto", args)
  if (status != 0L) stop("quarto render failed: quarto ", paste(args, collapse = " "), call. = FALSE)
}

# Stage the group's files into a throwaway project and render it.
render_staged <- function(name, files) {
  dir <- file.path(BUILD, name)
  unlink(dir, recursive = TRUE, force = TRUE)   # clean rebuild so removed files disappear
  dir.create(dir, recursive = TRUE, showWarnings = FALSE)
  for (f in files) {
    if (!file.exists(f)) stop("demo source missing: ", f, call. = FALSE)
    file.copy(f, file.path(dir, basename(f)), overwrite = TRUE, copy.mode = FALSE)
  }
  writeLines(c(
    "# Generated by tools/render-demos.R -- edit that script, not this file.",
    "project:",
    "  type: default",
    sprintf("  output-dir: %s%s/%s", up_to_root(dir), OUT, out_name[[name]])
  ), file.path(dir, "_quarto.yml"))
  quarto(c("render", dir))
}

render_project <- function(name, dir) {
  quarto(c("render", dir, "--output-dir",
           sprintf("%s%s/%s", up_to_root(dir), OUT, out_name[[name]])))
}

# ---- run ---------------------------------------------------------------------------------------
wanted <- commandArgs(trailingOnly = TRUE)
if (length(wanted)) {
  unknown <- setdiff(wanted, names(groups))
  if (length(unknown)) {
    stop("unknown demo group: ", paste(unknown, collapse = ", "),
         " (known: ", paste(names(groups), collapse = ", "), ")", call. = FALSE)
  }
} else {
  wanted <- names(groups)
}

for (name in wanted) {
  g <- groups[[name]]
  if (!is.null(g$stage)) render_staged(name, g$stage) else render_project(name, g$project)
  cat(sprintf("render-demos: %s -> %s/%s\n", name, OUT, out_name[[name]]))
}

# ---- hub page ----------------------------------------------------------------------------------
# Without this, /demos/day1/ is a 404 on GitHub Pages: only the Day-2 project produces an
# index.html, so the other folders have no directory index. One bookmarkable page beats nine URLs.
# Deliberately plain -- this is build output for the instructor, not a page of the course site.
links <- character()
for (name in names(groups)) {
  dir <- file.path(OUT, out_name[[name]])
  if (!dir.exists(dir)) next
  # A group that builds a whole site is linked once, at its home page.
  rel <- if (file.exists(file.path(dir, "index.html"))) {
    "index.html"
  } else {
    sort(list.files(dir, pattern = "\\.(html|pdf)$"))
  }
  links <- c(links,
             sprintf("<h2>%s</h2>", out_title[[name]]),
             "<ul>",
             sprintf("<li><a href=\"%s/%s\">%s/%s</a></li>", out_name[[name]], rel,
                     out_name[[name]], rel),
             "</ul>")
}
writeLines(c(
  "<!DOCTYPE html>",
  "<html lang=\"en\"><head><meta charset=\"utf-8\">",
  "<title>RaukR 2026 Quarto -- demo documents</title>",
  "<style>body{font-family:system-ui,sans-serif;max-width:44rem;margin:3rem auto;padding:0 1rem}",
  "h2{font-size:1.1rem;margin-top:2rem}li{margin:.3rem 0}</style>",
  "</head><body>",
  "<h1>Demo documents</h1>",
  "<p>The finished lab documents, rendered as participants render them. Not linked from the",
  "course site.</p>",
  links,
  "</body></html>"
), file.path(OUT, "index.html"))
cat(sprintf("render-demos: hub page -> %s/index.html\n", OUT))
